#!/bin/bash
/usr/bin/xterm -u8 -en UTF-8 -fa "Hack Nerd Font Mono" -fs 9 -bg black -fg grey -sl 0 +fbx -xrm "XTerm*metaSendsEscape:true" -xrm "XTerm*allowFontOps:true" -xrm "XTerm*allowTcapOps:true" -xrm "XTerm*allowWindowOps:true" -geometry 256x64 -e env TERM=xterm-256color /bin/bash -l
