(set-frame-font "DejaVu Sans Mono 10")
(load-theme 'wombat)
(menu-bar-mode -1)
(when window-system
  (tooltip-mode -1)
  (tool-bar-mode -1))


(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")))

(require 'org)

(custom-set-variables
 '(backup-by-copying t)
 '(backup-directory-alist `((".*" . "~/.filebackups")))
 '(auto-save-file-name-transforms `((".*" "~/.filebackups" t)))
 '(c-basic-offset 8)
 '(c-default-style "linux")
 '(column-number-mode t)
 '(delete-old-versions t)
 '(display-time-24hr-format t)
 '(display-time-mode t)
 '(european-calendar-style t)
 '(font-lock-maximum-decoration t)
 '(global-font-lock-mode t)
 '(history-length 999)
 '(indent-tabs-mode t)
 '(inhibit-startup-echo-area-message t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(kept-new-versions 99)
 '(kept-old-versions 99)
 '(line-number-mode t)
 '(make-backup-files t)
 '(mouse-drag-copy-region nil)
 '(mouse-wheel-follow-mouse t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount '(3 ((shift). 3)))
 '(mouse-yank-at-point t)
 '(org-agenda-files )
 '(org-agenda-files '("~/documents/agenda.org"))
 '(org-startup-folded nil)
 '(org-startup-indented t)
 '(org-hide-leading-stars t)
 '(org-todo-keywords
   '((sequence "TODO" "STARTED" "WAITING" "|" "DONE" "CANCELLED")))
 '(org-todo-keyword-faces
   '(("TODO" . (:foreground "green" :weight bold))
     ("STARTED" . (:foreground "cyan" :weight bold))
     ("WAITING" . (:foreground "red" :weight bold))
     ("DONE" . (:foreground "grey" :weight bold))
     ("CANCELLED" . (:foreground "grey" :weight bold))))
 '(prefer-coding-system 'utf-8)
 '(python-indent-guess-indent-offset nil)
 '(require-final-newline t)
 '(scroll-conservatively 1)
 '(scroll-preserve-screen-position t)
 '(scroll-step 1)
 '(show-paren-mode t)
 '(tab-width 8)
 '(transient-mark-mode t)
 '(uniquify-buffer-name-style 'post-forward)
 '(vc-make-backup-files t)
 '(version-control t)
)

(global-set-key (kbd "M-<up>") 'windmove-up)
(global-set-key (kbd "M-<down>") 'windmove-down)
(global-set-key (kbd "M-<right>") 'windmove-right)
(global-set-key (kbd "M-<left>") 'windmove-left)
(global-set-key (kbd "M-[ 1 ; 3 a") 'windmove-up)
(global-set-key (kbd "M-[ 1 ; 3 b") 'windmove-down)
(global-set-key (kbd "M-[ 1 ; 3 c") 'windmove-right)
(global-set-key (kbd "M-[ 1 ; 3 d") 'windmove-left)
(global-set-key (kbd "M-[ 1 ; 5 A") 'backward-paragraph)
(global-set-key (kbd "M-[ 1 ; 5 B") 'forward-paragraph)
(global-set-key (kbd "M-[ 1 ; 5 C") 'forward-word)
(global-set-key (kbd "M-[ 1 ; 5 D") 'backward-word)
(global-set-key (kbd "M-c") 'kill-ring-save)
(global-set-key (kbd "M-v") 'yank)
(global-set-key (kbd "M-x") 'kill-region)
(global-set-key (kbd "\C-x\C-m") 'execute-extended-command)
(global-set-key (kbd "C-n") 'new-scratchpad)
(global-set-key (kbd "C-w") 'backward-kill-word)
(global-set-key (kbd "C-c a") 'org-agenda)

(defun new-scratchpad ()
  (interactive)
  (switch-to-buffer (concat "scratch-" (number-to-string (abs (random))))))

(defalias 'yes-or-no-p 'y-or-n-p)

(add-hook 'before-save-hook 'delete-trailing-whitespace)
(delete-selection-mode 1)

(load "~/.ssh/emacs.secrets")
